# Generated by Django 4.0.5 on 2022-06-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='company',
            field=models.CharField(default='Honda', max_length=20),
            preserve_default=False,
        ),
    ]
